// main.cpp
#include <iostream>
#include <vector>

// This header is automatically generated by the ISPC compiler
#include "vector_add_ispc.h" 

int main() {
    const int N = 1024;
    
    std::vector<float> a(N, 1.0f);
    std::vector<float> b(N, 2.0f);
    std::vector<float> result(N, 0.0f);

    // Call the ISPC function to process the vector addition in parallel
    ispc::vector_add(a.data(), b.data(), result.data(), N);

    // Verify the results
    std::cout << "Result[0]: " << result[0] << " (Expected: 3.0)\n";
    std::cout << "Result[" << N-1 << "]: " << result[N-1] << " (Expected: 3.0)\n";

    return 0;
}
